### ISSUE TITLE
mid quiz : Mid-Task 2 is incomplete 

### ISSUE THREAD

**Issue by DumiduNadeera** [dhammika-marasinghe/Learn-OCaml#1]
I think you're missing capacity attributes in Engine feature can be solved as follows 

type oiltype = Disel| Petrol ;;
type options = {ac:bool ; gps:bool ; stereo:bool};;
type engine = {ot:oiltype ; capacity:int} ;;

type model = {en:engine ; op:options};;

let is_fulloption (x:model) : bool= 
if x.op.ac = true && x.op.gps=true && x.op.stereo=true then true else false ;;

let rec full_option (vl:model list) = 
match vl with 
|[] -> 0 
|hd::tl -> if (is_fulloption hd) then 1 + full_option tl else full_option tl ;;

**Comment by dhammikamare** [comment]
Yeah. Thanks
I'll update the answers.
